module FastXlsx
  VERSION: String

  class Error < StandardError
  end

  type cell = Numeric | String | Time | Date | Formula | URL | bool | nil | _ToS

  class Formula
    attr_reader expression: String
    def self.new: (_ToS expression) -> Formula
  end

  class URL
    attr_reader url: String
    def self.new: (_ToS url) -> URL
  end

  class Workbook
    def self.new: (?constant_memory: bool) -> Workbook
    def add_worksheet: (?String? name) -> Worksheet
    def to_xlsx: () -> String
    def save: (String path) -> void
  end

  class Format
    def self.new: (?bold: bool, ?italic: bool, ?underline: bool, ?num_format: String) -> Format
  end

  class Worksheet
    def write: (Integer row, Integer col, cell value, ?Format? format) -> void
    def append: (Array[cell] values, ?format: Format?) -> self
    def <<: (Array[cell] row) -> self
    def concat: (Array[Array[cell]] rows) -> self
    def set_column_width: (Integer | Range[Integer] columns, Numeric width) -> self
    def autofit: () -> self
    def autofilter: (Integer first_row, Integer first_col, Integer last_row, Integer last_col) -> self
    def next_row: () -> Integer
  end
end
